Repository GoogleCloudPlatform/k8s-cloud-provider, pull requests merged in 2023-06, with the labels that each got.

#122 Adds rgraph and rnode
  pkg/cloud/rgraph/builder.go
  pkg/cloud/rgraph/doc.go
  pkg/cloud/rgraph/graph.go
  pkg/cloud/rgraph/graph_test.go
  pkg/cloud/rgraph/rnode/attributes.go
  pkg/cloud/rgraph/rnode/builder.go
  pkg/cloud/rgraph/rnode/builder_test.go
  pkg/cloud/rgraph/rnode/fake/builder.go
  pkg/cloud/rgraph/rnode/fake/fake.go
  pkg/cloud/rgraph/rnode/fake/node.go
  pkg/cloud/rgraph/rnode/node.go
  pkg/cloud/rgraph/rnode/node_test.go
  pkg/cloud/rgraph/rnode/plan.go
  pkg/cloud/rgraph/rnode/plan_test.go
Labels: size/XXL, lgtm, approved

#116 Add RateLimiter.Observe to some missing paths
  pkg/cloud/gen.go
  pkg/cloud/gen/main.go
  pkg/cloud/ratelimit_test.go
Labels: needs-ok-to-test, lgtm, approved, size/M

#126 Add algo/actions
  pkg/cloud/rgraph/algo/actions/actions.go
  pkg/cloud/rgraph/algo/actions/actions_test.go
  pkg/cloud/rgraph/exec/action.go
  pkg/cloud/rgraph/exec/action_test.go
  pkg/cloud/rgraph/exec/event.go
  pkg/cloud/rgraph/exec/event_test.go
  pkg/cloud/rgraph/exec/executor_serial.go
  pkg/cloud/rgraph/exec/executor_test.go
  pkg/cloud/rgraph/rnode/builder.go
  pkg/cloud/rgraph/rnode/fake/fake.go
  pkg/cloud/rgraph/rnode/fake/node.go
Labels: lgtm, approved, size/L

#125 Wrap usage of []Event with EventList
  pkg/cloud/rgraph/exec/action.go
  pkg/cloud/rgraph/exec/action_test.go
  pkg/cloud/rgraph/exec/event.go
  pkg/cloud/rgraph/exec/event_test.go
  pkg/cloud/rgraph/exec/executor_serial.go
  pkg/cloud/rgraph/exec/executor_test.go
Labels: approved, size/L

#127 Adds algo/graphviz
  pkg/cloud/rgraph/algo/graphviz/graphviz.go
Labels: lgtm, approved, size/L

#128 Add algo/localplan
  pkg/cloud/rgraph/algo/localplan/local_plan.go
  pkg/cloud/rgraph/algo/localplan/local_plan_test.go
  pkg/cloud/rgraph/rnode/fake/builder.go
  pkg/cloud/rgraph/rnode/fake/fake.go
  pkg/cloud/rgraph/rnode/fake/node.go
Labels: lgtm, approved, size/L

#129 Export Fake types; Add EZ graph builder
  pkg/cloud/rgraph/testing/ez/ez.go
  pkg/cloud/rgraph/testing/ez/ez_test.go
  pkg/cloud/rgraph/testing/ez/factories.go
Labels: lgtm, approved, size/L

#130 Adding concept of APIGroup to Services
  pkg/cloud/gen.go
  pkg/cloud/gen/main.go
  pkg/cloud/gen_test.go
  pkg/cloud/meta/compute_services.go
  pkg/cloud/meta/meta.go
  pkg/cloud/meta/service.go
  pkg/cloud/mock/mock.go
  pkg/cloud/utils.go
  pkg/cloud/utils_test.go
Labels: size/XXL, lgtm, approved
