Repository GoogleCloudPlatform/k8s-cloud-provider, pull requests merged in 2023-11, with the labels that each got.

#139 Adds algo/transitive_closure
  pkg/cloud/rgraph/algo/trclosure/transitive_closure.go
  pkg/cloud/rgraph/algo/trclosure/transitive_closure_test.go
  pkg/cloud/rgraph/rnode/all/new.go
  pkg/cloud/rgraph/rnode/fake/builder.go
  pkg/cloud/rgraph/rnode/fake/fake.go
Labels: lgtm, approved, size/XL

#138 Fake object enhancements for testing
  pkg/cloud/rgraph/rnode/fake/builder.go
  pkg/cloud/rgraph/rnode/fake/fake.go
Labels: approved, size/M

#152 fix NewBuilderByID after rebase
  pkg/cloud/rgraph/rnode/all/new.go
Labels: lgtm, approved, size/XS

#151 update ParseResourceURL function to support legacy URLs
  pkg/cloud/utils.go
  pkg/cloud/utils_test.go
Labels: lgtm, approved, size/M

#155 Fix mock hooks, add options argument, add compile-time verification
  pkg/cloud/mock/mock.go
Labels: needs-ok-to-test, lgtm, approved, size/XL

#159 Support the global NEG.
  pkg/cloud/gen.go
  pkg/cloud/gen_test.go
  pkg/cloud/meta/compute_services.go
Labels: size/XXL, lgtm, approved, ok-to-test
