Repository GoogleCloudPlatform/k8s-cloud-provider, pull requests merged in 2023-03, with the labels that each got.

#77 Extend RateLimiter interface with observe functionality
  pkg/cloud/gce_projects.go
  pkg/cloud/gen.go
  pkg/cloud/gen/main.go
  pkg/cloud/gen_test.go
  pkg/cloud/ratelimit.go
  pkg/cloud/service.go
Labels: needs-ok-to-test, lgtm, approved, size/XL

#80 Expose Patch API for BackendService resource
  pkg/cloud/gen.go
  pkg/cloud/meta/meta.go
Labels: lgtm, approved, size/L, ok-to-test

#81 Observe
  Makefile
  go.mod
  go.sum
  pkg/cloud/context.go
  pkg/cloud/gen.go
  pkg/cloud/gen/main.go
  pkg/cloud/observe.go
  pkg/cloud/observe_test.go
  pkg/cloud/ratelimit.go
Labels: size/XXL, lgtm, approved

#87 Fix object package typo.
  pkg/cloud/mock/mock.go
Labels: lgtm, approved, size/XS

#86 Upstream lint fixes.
  pkg/cloud/meta/service.go
Labels: lgtm, approved, size/XS

#85 Adds global OperationsUseWait which switches Operation.Get to Operation.Wait; manual e2e testing
  Makefile
  e2e/addresses_test.go
  e2e/doc.go
  e2e/observe_test.go
  e2e/regions_test.go
  e2e/testmain_test.go
  e2e/zones_test.go
  go.mod
  go.sum
  pkg/cloud/op.go
  pkg/cloud/service.go
  vendor/github.com/kr/pretty/.gitignore
  vendor/github.com/kr/pretty/License
  vendor/github.com/kr/pretty/Readme
  vendor/github.com/kr/pretty/diff.go
  vendor/github.com/kr/pretty/formatter.go
  vendor/github.com/kr/pretty/pretty.go
  vendor/github.com/kr/pretty/zero.go
  vendor/github.com/kr/text/License
  vendor/github.com/kr/text/Readme
  vendor/github.com/kr/text/doc.go
  vendor/github.com/kr/text/indent.go
  vendor/github.com/kr/text/wrap.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#90 Add InstanceGroupManager, InstanceTemplate APIs
  pkg/cloud/gen.go
  pkg/cloud/gen_test.go
  pkg/cloud/meta/meta.go
Labels: size/XXL, lgtm, approved

#88 Refactor code generator.
  pkg/cloud/gen.go
  pkg/cloud/gen/main.go
Labels: lgtm, approved, size/XL

#92 Fix1
  pkg/cloud/gen.go
Labels: lgtm, approved, size/XS
