Repository GoogleCloudPlatform/k8s-cloud-provider, pull requests merged in 2023-05, with the labels that each got.

#110 Minor doc and naming fixes
  pkg/cloud/api/copy.go
  pkg/cloud/api/doc.go
  pkg/cloud/api/resource.go
  pkg/cloud/api/resource_test.go
Labels: lgtm, approved, size/S

#111 Fix issue where Set() was validiting too much; simplify conversion code
  pkg/cloud/api/resource.go
  pkg/cloud/api/resource_test.go
Labels: lgtm, approved, size/L

#112 Introduce a package-private type contextKey.
  pkg/cloud/observe.go
Labels: lgtm, approved, size/XS

#115 Remove extra wrapping of errors in visit
  pkg/cloud/api/visit.go
Labels: lgtm, approved, size/S

#113 Ignore ServerResponse field in check
  pkg/cloud/api/check.go
Labels: lgtm, approved, size/S

#114 Ignore special field ServerResponse in Fill()
  pkg/cloud/api/fill.go
  pkg/cloud/api/fill_test.go
Labels: lgtm, approved, size/S

#117 Run go mod vendor; go mod tidy
  go.mod
  go.sum
  vendor/github.com/kr/pretty/License
  vendor/github.com/kr/pretty/diff.go
  vendor/github.com/kr/pretty/formatter.go
  vendor/github.com/kr/pretty/pretty.go
  vendor/github.com/rogpeppe/go-internal/LICENSE
  vendor/github.com/rogpeppe/go-internal/fmtsort/mapelem.go
  vendor/github.com/rogpeppe/go-internal/fmtsort/mapelem_1.11.go
  vendor/github.com/rogpeppe/go-internal/fmtsort/sort.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#118 Add String() for ResourceID
  pkg/cloud/utils.go
  pkg/cloud/utils_test.go
Labels: lgtm, approved, size/M

#119 Rename FrozenResource -> Resource, Resource -> MutableResource
  pkg/cloud/api/frozen_resource.go
  pkg/cloud/api/mutable_resource.go
  pkg/cloud/api/resource.go
  pkg/cloud/api/resource_test.go
Labels: size/XXL, lgtm, approved

#120 Package exec implements execution of a graph of Action and Events.
  pkg/cloud/rgraph/exec/action.go
  pkg/cloud/rgraph/exec/action_test.go
  pkg/cloud/rgraph/exec/doc.go
  pkg/cloud/rgraph/exec/event.go
  pkg/cloud/rgraph/exec/event_test.go
  pkg/cloud/rgraph/exec/executor.go
  pkg/cloud/rgraph/exec/executor_serial.go
  pkg/cloud/rgraph/exec/executor_serial_test.go
  pkg/cloud/rgraph/exec/executor_test.go
  pkg/cloud/rgraph/exec/tracer.go
  pkg/cloud/rgraph/exec/tracer_graphviz.go
Labels: size/XXL, lgtm, approved

#121 Make SerialExecutor bail on bad arguments earlier
  pkg/cloud/rgraph/exec/executor.go
  pkg/cloud/rgraph/exec/executor_serial.go
  pkg/cloud/rgraph/exec/executor_serial_test.go
Labels: lgtm, approved, size/M

#123 Support IPv6 Address in mock
  pkg/cloud/mock/mock.go
Labels: needs-ok-to-test, lgtm, approved, size/S
