Repository GoogleCloudPlatform/k8s-cloud-provider, pull requests merged in 2024-09, with the labels that each got.

#225 Add Fallback Cleanup
  e2e/tcproute_test.go
  e2e/testmain_test.go
Labels: lgtm, approved, size/L

#226 Fix calls to NetworkServices List
  pkg/cloud/gen.go
  pkg/cloud/gen/main.go
Labels: lgtm, approved, size/S

#228 Add resource key to observer CallContext.
  pkg/cloud/context.go
  pkg/cloud/gen.go
  pkg/cloud/gen/main.go
Labels: lgtm, approved, size/XL

#229 Add option for sending custom headers in requests.
  pkg/cloud/gen.go
  pkg/cloud/gen/main.go
  pkg/cloud/option.go
Labels: lgtm, approved, size/XL

#230 Fix observe_test.go
  e2e/observe_test.go
  pkg/cloud/gen.go
Labels: lgtm, approved, size/S
