Repository GoogleCloudPlatform/k8s-cloud-provider, pull requests merged in 2024-05, with the labels that each got.

#194 Add -race option to make test
  Makefile
Labels: lgtm, approved, size/XS

#199 Add impersonation option to e2e tests
  e2e/testmain_test.go
  go.sum
  vendor/google.golang.org/api/impersonate/doc.go
  vendor/google.golang.org/api/impersonate/idtoken.go
  vendor/google.golang.org/api/impersonate/impersonate.go
  vendor/google.golang.org/api/impersonate/user.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#198 Address comments for healthcheck update tests
  e2e/healthcheck_update_test.go
Labels: lgtm, approved, size/S

#196 Parallel executor - remove default timeout value
  pkg/cloud/rgraph/algo/parallel_queue.go
  pkg/cloud/rgraph/algo/parallel_queue_test.go
  pkg/cloud/rgraph/algo/trclosure/transitive_closure.go
  pkg/cloud/rgraph/exec/executor.go
  pkg/cloud/rgraph/exec/executor_parallel.go
  pkg/cloud/rgraph/exec/executor_parallel_test.go
Labels: lgtm, approved, size/L

#197 Add TimeoutOption to serial executor
  pkg/cloud/rgraph/exec/executor_serial.go
  pkg/cloud/rgraph/exec/executor_serial_test.go
Labels: lgtm, approved, size/M

#200 Add new types of rate limiters
  e2e/testmain_test.go
  pkg/cloud/ratelimit.go
  pkg/cloud/ratelimit_test.go
Labels: lgtm, approved, size/L

#208 Add region neg support
  pkg/cloud/gen.go
  pkg/cloud/gen_test.go
  pkg/cloud/meta/compute_services.go
Labels: size/XXL, lgtm, approved, ok-to-test
