Repository GoogleCloudPlatform/k8s-cloud-provider, pull requests merged in 2024-04, with the labels that each got.

#183 Fix TCP Route test
  e2e/tcproute_test.go
  e2e/test-helpers.go
Labels: lgtm, approved, size/M

#185 e2e test - Backend service update
  e2e/backend_service_update_test.go
  e2e/tcproute_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#188 Move functions using global test flags to *_test file
  e2e/tcproute_test.go
  e2e/test-helpers.go
Labels: lgtm, approved, size/S

#182 Implement BackendService traits
  pkg/cloud/rgraph/rnode/backendservice/backendservice_test.go
  pkg/cloud/rgraph/rnode/backendservice/type_trait.go
  tools/checkcov.yaml
Labels: lgtm, approved, size/XL

#187 Fix BackendService update test
  e2e/backend_service_update_test.go
  e2e/tcproute_test.go
Labels: lgtm, approved, size/S

#192 Add Healthcheck update test
  e2e/healthcheck_update_test.go
Labels: lgtm, approved, size/M

#195 fix: Add MinimumRateLimiter configured to 50ms to e2e tests
  e2e/testmain_test.go
Labels: lgtm, approved, size/XS
