Repository GoogleCloudPlatform/k8s-cloud-provider, pull requests merged in 2024-01, with the labels that each got.

#165 document impliedVersion() rules for mutable resource
  pkg/cloud/api/mutable_resource.go
Labels: lgtm, approved, size/M

#167 update year in gen files
  pkg/cloud/gen.go
  pkg/cloud/gen_test.go
Labels: lgtm, approved, size/XS

#168 Wrap coverage run in shell, fix inconsistency in results
  Makefile
  tools/checkcov
  tools/checkcov.go
  tools/checkcov.yaml
Labels: lgtm, approved, size/L

#148 add tcp route
  pkg/cloud/rgraph/rnode/all/new.go
  pkg/cloud/rgraph/rnode/all/resource_builder.go
  pkg/cloud/rgraph/rnode/tcproute/builder.go
  pkg/cloud/rgraph/rnode/tcproute/node.go
  pkg/cloud/rgraph/rnode/tcproute/ops.go
  pkg/cloud/rgraph/rnode/tcproute/tcproute.go
  pkg/cloud/rgraph/rnode/tcproute/tcproute_test.go
  pkg/cloud/rgraph/rnode/tcproute/type_trait.go
  pkg/cloud/rgraph/testing/ez/ez.go
  pkg/cloud/rgraph/testing/ez/factories.go
  pkg/cloud/rgraph/workflow/testlib/lb/tcproute.go
  pkg/cloud/utils.go
Labels: lgtm, approved, ok-to-test, size/XL

#166 Add check that Alpha and Beta are subsets of GA fields
  pkg/cloud/api/check.go
  pkg/cloud/api/check_test.go
  pkg/cloud/api/converter_test_types/converter-structs.go
  pkg/cloud/api/diff.go
  pkg/cloud/api/diff_test.go
  pkg/cloud/api/mutable_resource.go
  pkg/cloud/api/resource_test.go
  tools/checkcov.yaml
Labels: lgtm, approved, size/XL
