Repository GoogleCloudPlatform/k8s-cloud-provider, pull requests merged in 2024-06, with the labels that each got.

#209 Fixes the serial executor test
  pkg/cloud/rgraph/exec/action_test.go
  pkg/cloud/rgraph/exec/executor_parallel_test.go
  pkg/cloud/rgraph/exec/executor_serial_test.go
Labels: lgtm, approved, size/M

#204 Change type traits constrains logic.
  pkg/cloud/api/check.go
  pkg/cloud/api/check_test.go
  pkg/cloud/api/fill.go
  pkg/cloud/api/fill_test.go
  pkg/cloud/api/type_trait.go
  pkg/cloud/rgraph/rnode/backendservice/backendservice_test.go
  pkg/cloud/rgraph/rnode/backendservice/builder.go
  pkg/cloud/rgraph/rnode/backendservice/type_trait.go
  pkg/cloud/rgraph/rnode/healthcheck/healthcheck_test.go
  pkg/cloud/rgraph/rnode/healthcheck/type_trait.go
Labels: lgtm, approved, size/XL

#206 Remove latency measurements from TickerRateLimiter tests
  pkg/cloud/ratelimit_test.go
Labels: lgtm, approved, size/S

#205 Implement retriable action
  pkg/cloud/rgraph/exec/retrieable_action.go
  pkg/cloud/rgraph/exec/retrieable_action_test.go
Labels: lgtm, approved, size/L

#210 Split TickerRateLimiter test
  pkg/cloud/ratelimit_test.go
Labels: lgtm, approved, size/XS
