Repository GoogleCloudPlatform/k8s-cloud-provider, pull requests merged in 2024-08, with the labels that each got.

#221 Accept 400 as a valid error code for zone/region that does not exist
  e2e/regions_test.go
  e2e/zones_test.go
Labels: lgtm, approved, size/S

#219 Add EnsureBackendService test
  e2e/backend_service_update_test.go
Labels: lgtm, approved, size/M

#223 Add location method to Key.
  pkg/cloud/meta/key.go
  pkg/cloud/meta/key_test.go
Labels: lgtm, approved, size/S

#218 Add EnsureTcpRoute test
  e2e/tcproute_test.go
Labels: lgtm, approved, size/M

#222 Fix compression mode
  pkg/cloud/rgraph/rnode/backendservice/type_trait.go
Labels: lgtm, approved, size/XS

#217 Add BackendServiceMetadataUpdate test
  e2e/backend_service_update_test.go
  e2e/tcproute_test.go
Labels: lgtm, approved, size/L

#224 Add support for region target TCP proxies.
  pkg/cloud/gen.go
  pkg/cloud/gen_test.go
  pkg/cloud/meta/compute_services.go
Labels: size/XXL, lgtm, approved
